services:
  bot:
    image: leaftail/save-from-e621-tg-bot
    env_file:
      - .env
    environment:
      - DOCKER=true
      - SAVE_TO_PATH=/usr/bot/images/
    volumes:
      - ./docker-images:/usr/bot/images/